---
title: Install and Upgrade
crumbs:
  - "3.x"
---

### Installation

1. Download the latest version of [Traq](https://traq.io) and unzip the archive.
2. Upload the contents of the `upload` directory to your server.
3. Open the web address of the directory you uploaded [Traq](https://traq.io) to.
4. Follow the installation steps.

#### Installing from repository

Clone the [Traq](https://traq.io) repository then checkout the latest version.

    git clone --recursive https://github.com/nirix/traq
    git checkout v3.6.0

Then follow the last two steps above.

### Upgrading

Upgrading is very similar to the installation, download the latest version of
[Traq](https://traq.io) and unzip the archive, then upload the contents of the
`upload` directory.

Then simply open the web address of your installation and head to `/install/upgrade.php`.
