---
title: Permissions
crumbs:
  - "3.x"
---

Traq features a flexible, easy to use, per-project permission system.

### Groups and Roles

There are two sets of permissions in Traq, one for user groups and another for project roles.

#### Groups

Group permissions are pretty self explanatory, they allow or disallow what a group of users can do.

#### Roles

Role permissions are for members of a project, such as managers, developers and testers.

### How They Work

Permissions work in a specific way. Role permissions take priority over group permissions.

For example, let's say a user belongs to the group `Employee` and the role `Developer` and the `Employee` group cannot
create tickets but the `Developer` role can.

There is, however, one group that cannot be limited, the Admin group. The system is designed
to allow Admins to do everything.

### Private Projects

The permission system makes it very easy to create private projects.

The best way is to set all group permissions to `Deny`, then add users to a group or role with
the permissions you want to grant them.
