Traq Documentation
------------------

* Traq 3.x
    * [Install and Upgrade](<?=Request::basePath('docs/3/installation')?>)
    * [API](<?=Request::basePath('docs/3/api')?>)
    * [Localisation](<?=Request::basePath('docs/3/localisation')?>)
    * [Permissions](<?=Request::basePath('docs/3/permissions')?>)
    * [Plugins](<?=Request::basePath('docs/3/plugins')?>)
        * [Creating Plugins](<?=Request::basePath('docs/3/plugins/creating')?>)
        * [Translating Plugins](<?=Request::basePath('docs/3/plugins/translating')?>)
* Server Configuration
    * [Apache](<?=Request::basePath('docs/server-configuration/apache')?>)
