Traq Documentation
------------------

* Traq 3.x
    * [API](<?php echo Request::base('docs/3/api')?>)
    * [Localisation](<?php echo Request::base('docs/3/localisation')?>)
    * [Permissions](<?php echo Request::base('docs/3/permissions')?>)
    * [Plugins](<?php echo Request::base('docs/3/plugins')?>)
        * [Creating Plugins](<?php echo Request::base('docs/3/plugins/creating')?>)
        * [Translating Plugins](<?php echo Request::base('docs/3/plugins/translating')?>)
* Server Configuration
    * [Apache](<?=Request::base('docs/server-configuration/apache')?>)