---
title: Translating Plugins
crumbs:
  - "3.x"
  -
    - "3.x/plugins"
    - Plugins
---

Plugin translation strings are stored as a `key => value` array in the plugins `locale` directory
with the filename representing the translations short name (`enau.php`).

    // vendor/traq/plugins/my_plugin/locale/enau.php
    return array(
        'myplugin.admincp.welcome' => "Welcome to the AdminCP for MyPlugin"
    );

Traq will handle the loading of the file.
