## Translating

Traq ships with an english language file as default. Alternative languages can be found in the [languages forum](http://forum.traq.io/forumdisplay.php?fid=35).

The files linked there need to be downloaded and added to the `vendor/traq/locale` directory.

### Own translations

To create your own translation just copy the English language file (`enus.php`) and modify its content to your needs.

### Activating the newly added language file

To activate the language you just added there are 2 possibilities:

- Choose that language in AdminCP as default for every user
- Choose that language in UserCP only for your user
