Managing Plugins
----------------

All plugins are placed into the `vendor/traq/plugins` directory.

### Before Installing

Before installing a plugin, it is best to verify its legitimacy as a plugin
and doesn't contain anything that could compromise your installation.

It is also recommended to keep an up-to-date backup of your database.

### Installing

To install plugins located in the `plugins` directory, head to the AdminCP > Plugins page.
There you will see a list of available plugins with an option to install.

When a plugin is installed, queries that modify the database are executed.

### Uninstalling

Uninstalling can be done on the same page by using the `Uninstall` option.

### Enabling and Disabling

Plugins that are disabled keep any database changes but the plugins features are simply
turned off.
