---
title: Moving Tickets
crumbs:
  - "3.x"
  - "Tickets"
---

If you have multiple projects setup, you can move a ticket from one project to another.

To move a ticket, bring up the page for the ticket you want to move and look for a `Move` link at the top-right of the
Ticket information section.

When moving a ticket, you will need to specify a new `Milestone`, `Version`, `Component` and possibly the assignee.
