---
title: Apache
crumbs:
  - "Server Configuration"
---

To run Traq on Apache you will need the `mod_rewrite` module.

## Rewrite rules

Some servers are setup differently and require different rewrite rules. The ones listed on this page have had the most
success on varying setups.

### Default rewrite rules

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php/$1 [L]

### Alternate rewrite rules

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php?/$1 [L,QSA]
